parameters:
    database_driver:   pdo_sqlite
#    database_host:     127.0.0.1
#    database_port:     8889
    database_name:     vpa
    database_path:  ":memory:"
#    database_user:     root
#    database_password: root

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
