virtual_persist_api:
    resource: "@VirtualPersistBundle/Controller/"
    type:     annotation

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

account_register:
   pattern:  /register
   defaults: { _controller: VirtualPersistBundle:Account:register }

account_create:
   pattern:  /register/create
   defaults: { _controller: VirtualPersistBundle:Account:create }
