parameters:
    database_driver:   pdo_mysql
    database_host:     ~
    database_port:     ~
    database_name:     vpa
    database_user:     ~
    database_password: ~
    database_memory:   false
    database_path:     "db/data.sqlite"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
