language: php

php: 5.4
#  - 5.3
#  - 5.4

before_script:
  - cd ./symfony
  - curl -s https://getcomposer.org/installer | php
  - rm composer.lock
  - ./composer.phar -v -o --dev --no-progress install
  - php app/console doctrine:schema:update --force

script: ./bin/phpunit -c ./app
