language: php

php: 5.4
#  - 5.3
#  - 5.4

before_script:
  - cd ./symfony
  - curl -s https://getcomposer.org/installer | php
  - ./composer.phar --dev --no-progress install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - php app/console clear:cache --env=test
  - php app/console assetic:dump --env=test

script: ./bin/phpunit -c ./app
