language: php

php: 5.4
#  - 5.3
#  - 5.4

before_script:
  - mysql -e 'create database vpa;'
  - cd ./symfony
  - composer -v -o --no-progress update
  - php ./app/console cache:clear -e=test

script: ./vendor/bin/phpunit -c ./app --coverage-text

