parameters:
#    virtual_persist_api_virtual_persist.example.class: VirtualPersistAPI\VirtualPersistBundle\Example

services:
#    virtual_persist_api_virtual_persist.example:
#        class: %virtual_persist_api_virtual_persist.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
